name: '@mi-sec/ip build'

on:
  push:
    tags-ignore:
      - '*.*'
    paths:
      - 'packages/ip/**'
  pull_request:
    tags-ignore:
      - '*.*'
    paths:
      - 'packages/ip/**'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: 'Set Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn --cwd packages/ip/ install
      - name: Lint
        run: yarn --cwd packages/ip/ lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: 'Set Node.js ${{ matrix.node }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm dependencies
        run: yarn --cwd packages/ip/ install
      - name: Run tests
        run: yarn --cwd packages/ip/ test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
