name: '@mi-sec/network-cidr action'

on:
  push:
    tags-ignore:
      - '*.*'
    paths:
      - 'packages/network-cidr/**'
  pull_request:
    tags-ignore:
      - '*.*'
    paths:
      - 'packages/network-cidr/**'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci --silent --prefix packages/network-cidr/
      - run: npm run --prefix packages/network-cidr/ lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm dependencies
        run: npm ci --silent --prefix packages/network-cidr/
      - name: run tests
        run: npm run --prefix packages/network-cidr/ test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ${{ github.workspace }}/packages/network-cidr/coverage/lcov.info
          github-token: ${{ secrets.ACCESS_TOKEN }}
