name: '@mi-sec/port-scanner action'

on:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'packages/port-scanner/**'
  pull_request:
    tags-ignore:
      - '**'
    paths:
      - 'packages/port-scanner/**'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci --silent --prefix packages/port-scanner/
      - run: npm run --prefix packages/port-scanner/ lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm dependencies
        run: npm ci --silent --prefix packages/port-scanner/
      - name: run tests
        run: npm run --prefix packages/port-scanner/ test
      - name: codecov
        uses: codecov/codecov-action@v1
        with:
          file: packages/port-scanner/coverage/lcov.info
